### ISSUE TITLE
build without text no longer work

### ISSUE THREAD

**Issue by kocoten1992** [shaka-project/shaka-player#3863]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.3.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**What did you do?**
```
git clone https://github.com/google/shaka-player
cd shaka-player
python build/build.py +@complete -@polyfill -@text
```

**What did you expect to happen?**
it should work

**What actually happened?**
```
[INFO] Compiling the library (ui, release)...
/tmp/shaka-player/lib/player.js:37:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "shaka.text.WebVttGenerator" never defined.
  37| goog.require('shaka.text.WebVttGenerator');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
[ERROR] Build failed
```

**Comment by MadMods96** [comment]
Respected sir/Madam,

I am Madhusudan Pareek , a computer science undergraduate , I have just entered to my 4th semester at TC College affiliated with Savitri Bai Phule Pune University. I am new to open source but I am well aware of JavaScript , Nodejs, PostgreSQL, MySQL, HTML,CSS, bootstrap, React and also good knowledge of making rest api’s. I would love to contribute to your organization. Currently I had worked with an organization ‘IBKAAS’ as an intern and developed their backend with NodeJS ( express )and PostgreSQL and now I’m looking for open source..

Hoping to hear from you soon.

Regards

Madhusudan

**Comment by naktinis** [comment]
To add some context, the error in its current form appeared in 0845843b651c32b3081772a39947b0202f044094.

Before that, there was already dependency on `@text`, which was for the first time introduced in faa1e52902bcf2b6d9d6b7067794236c41ec0cee.
